# Site settings
title: Yubolun
logo: book.png
email: feibilanceon@gmail.com
description: Yubolun's DEV Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yubolun.com" # the base hostname & protocol for your site
imageurl: "https://yubolun.com/images/"
twitter_username: discountifu
# weibo_id: 2056725322
github_username:  discountry
codepen_username:  discountry
# wordpress_site: "https://yubolun.com"

timezone: Asia/Shanghai

# Build settings
excerpt_separator: <!--more-->
permalink: pretty
markdown: kramdown
highlighter: rouge

#Pagination
paginate: 6

#Podcast
lang: zh-Hans
subtitle: Dev Blog
author: yubolun

